### ISSUE TITLE
从 Qcm, ElectronNCM, feeluown, YesPlayMusic(latest commit) 直接获取歌曲id

### ISSUE THREAD

**Issue by mokurin000** [kangxiaoju/waybar-netease-music-lyrics#1]
可以作为参考看看 https://github.com/waylyrics/waylyrics/blob/bb5ef3ef2d0202da9215baad548216d27d5505af/src/sync/player.rs#L315

**Comment by kangxiaoju** [comment]
这个后面解决了，这个版本太早了，没有发布上来
